### ISSUE TITLE
How to create INP file

### ISSUE THREAD

**Issue by anniemark271983** [modelcreate/model-view#53]
Hi

can any one help me how can i create my own INP file using node js coding

**Comment by lbutler** [comment]
Check out the epanet-js library that allows you to use any of the original epanet API functions that also include the ability to programatically create a network and save it to INP or run a simulation.

https://github.com/modelcreate/epanet-js

Some references that may be helpful:
https://epanetjs.com/introduction/examples/#new-model-builder-api
https://epanetjs.com/api/project-functions/network-node/#addnode

**Comment by anniemark271983** [comment]
import {Project, Workspace} from 'epanet-js'

const ws = new Workspace();
const model = new Project(ws);

model.init('report.rpt', 'out.bin', 0, 0);

const n1Index = model.addNode('N1', NodeType.Junction);
const n2Index = model.addNode('N2', NodeType.Junction);
model.setJunctionData(n1Index, 700, 0, '');
model.setJunctionData(n2Index, 400, 0, '');

const l1Index = model.addLink('L1',LinkType.Pipe,'N1','N2')


This code is ok but how can i save model as inp file can you please help me on this
